///////////allergies

export const GET_ALLERGIES = 'GET_ALLERGIES'
export const GET_ALLERGIES_SUCCESS = 'GET_ALLERGIES_SUCCESS'
export const GET_ALLERGIES_FAILED = 'GET_ALLERGIES_FAILED'

export const ADD_ALLERGIES = "ADD_ALLERGIES"
export const ADD_ALLERGIES_SUCCESS = "ADD_ALLERGIES_SUCCESS"
export const ADD_ALLERGIES_FAILED = "ADD_ALLERGIES_FAILED"

export const GET_DOCUMENT='GET_DOCUMENT'
export const GET_DOCUMENT_SUCCESS ='GET_DOCUMENT_SUCCESS'
export const GET_DOCUMENT_FAILED = 'GET_DOCUMENT_FAILED'

export const DELETE_ALLERGIES = 'DELETE_ALLERGIES'
export const DELETE_ALLERGIES_SUCCESS = 'DELETE_ALLERGIES_SUCCESS'
export const DELETE_ALLERGIES_FAILED = 'DELETE_ALLERGIES_FAILED'


export const ADD_DOCUMENT = "ADD_DOCUMENT"
export const ADD_DOCUMENT_SUCCESS = "ADD_DOCUMENT_SUCCESS"
export const ADD_DOCUMENT_FAILED = "ADD_DOCUMENT_FAILED"

export const DELETE_DOCUMENT = 'DELETE_DOCUMENT'
export const DELETE_DOCUMENT_SUCCESS = 'DELETE_DOCUMENT_SUCCESS'
export const DELETE_DOCUMENT_FAILED = 'DELETE_DOCUMENT_FAILED'


//////diagnosies

export const GET_DIAGNOSIS = 'GET_DIAGNOSIS'
export const GET_DIAGNOSIS_SUCCESS = 'GET_DIAGNOSIS_SUCCESS'
export const GET_DIAGNOSIS_FAILED = 'GET_DIAGNOSIS_FAILED'

export const DELETE_DIAGNOSIS = 'DELETE_DIAGNOSIS'
export const DELETE_DIAGNOSIS_SUCCESS = 'DELETE_DIAGNOSIS_SUCCESS'
export const DELETE_DIAGNOSIS_FAILED = 'DELETE_DIAGNOSIS_FAILED'



export const CREATE_MEMORY = 'CREATE_MEMORY'
export const CREATE_MEMORY_SUCCESS = 'CREATE_MEMORY_SUCCESS'
export const CREATE_MEMORY_FAILED = 'CREATE_MEMORY_FAILED'

export const CREATE_USER = 'CREATE_USER'
export const CREATE_USER_SUCCESS = 'CREATE_USER_SUCCESS'
export const CREATE_USER_FAILED = 'CREATE_USER_FAILED'

export const USER_LOGIN = 'USER_LOGIN'
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS'
export const USER_LOGIN_FAILED = 'USER_LOGIN_FAILED'

export const LOGOUT = 'LOGOUT'
export const UPDATE_ID = 'UPDATE_ID'

export const UPDATE_MEMORY = 'UPDATE_MEMORY'
export const UPDATE_MEMORIES_SUCCESS = 'UPDATE_MEMORIES_SUCCESS'
export const UPDATE_MEMORIES_FAILED = 'UPDATE_MEMORIES_FAILED'

export const DELETE_MEMORY = 'DELETE_MEMORY'
export const DELETE_MEMORY_SUCCESS = 'DELETE_MEMORY_SUCCESS'
export const DELETE_MEMORY_FAILED = 'DELETE_MEMORY_FAILED'

export const MAKENULLID = 'MAKENULLID'